apiVersion: v1
data:
  local_config.yaml: |
    server:
      http:
        hostname: localhost
        port: 8000
        static:
          production:
            /public: server/public
            /assets: dist/assets
            /dist: dist
      redis:
        port: 6379
        host: redis.kubesphere-system.svc
      redisTimeout: 5000
      sessionTimeout: 7200000
      apiServer:
        url: http://ks-apiserver
        wsUrl: ws://ks-apiserver

    client:
      version:
        kubesphere: v4.1.2
        kubernetes: v1.23.15
      enableKubeConfig: true
      enableNodeListTerminal: true
kind: ConfigMap
metadata:
  name: ks-console-config
  namespace: react-sample-proj

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ks-console
    tier: frontend
  name: ks-console
  namespace: react-sample-proj
spec:
  ports:
    - name: nginx
      port: 80
      protocol: TCP
      targetPort: 8000
      nodePort: 30882
  selector:
    app: ks-console
    tier: frontend
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ks-console
    tier: frontend
  name: ks-console
  namespace: react-sample-proj
spec:
  replicas:  1
  selector:
    matchLabels:
      app: ks-console
      tier: frontend
  template:
    metadata:
      labels:
        app: ks-console
        tier: frontend
    spec:
      containers:
        - name: ks-console
          image: $REGISTRY/$DOCKERHUB_NAMESPACE/$APP_NAME:$BUILD_NUMBER
          imagePullPolicy: IfNotPresent
          env:
          resources:
            limits:
              cpu: 1
              memory: 1024Mi
            requests:
              cpu: 20m
              memory: 100Mi
          livenessProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 15
            timeoutSeconds: 15
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 8
          volumeMounts:
            - name: ks-console-config
              mountPath: /opt/kubesphere/console/configs/local_config.yaml
              subPath: local_config.yaml
            - name: host-time
              mountPath: /etc/localtime
              readOnly: true
      volumes:
        - configMap:
            name: ks-console-config
            defaultMode: 420
            items:
              - key: local_config.yaml
                path: local_config.yaml
          name: ks-console-config
        - hostPath:
            path: /etc/localtime
            type: ""
          name: host-time
